### ISSUE TITLE
build exception

### ISSUE THREAD

**Issue by ryantan1** [iFLYOS-OPEN/ShowCore-Open#3]
Hi,

showcore-open 下载后编译出现 kotlin-gradle-plugin:1.3.21找不到，从LOG中提示的链接中也找不到对应的pom， 确认机子能访问 google服务器。
将这个 kotlin-gradle-plugin临时注了， 发现androidx.navigation:navigation-safe-args-gradle-plugin:2.1.0-alpha04 也无法下载。

LOG如下：
--------------------
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'ShowCore-Open'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21.
     Required by:
         project :
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
               > sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
      > Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21.
         > Could not get resource 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
            > Could not GET 'https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.21/kotlin-gradle-plugin-1.3.21.pom'.
--------------------
请看下什么原因， 相关支持有相应的群吗？
谢谢

**Comment by seasonyuu** [comment]
这个是很明显的网络问题哈，科学上网一下就可以解决了
